[versions]
agp = "8.3.0"
kotlin = "2.3.0"
compose-bom = "2024.02.00"
coroutines = "1.8.0"
commons-compress = "1.26.0"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.12.0" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version = "2.7.0" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version = "2.7.0" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
commons-compress = { group = "org.apache.commons", name = "commons-compress", version.ref = "commons-compress" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
